name: ci

on:
  push:
    branches:
      - 'master'
env:
  IMAGE_NAME: luanleiteti/chatapp:latest
  PROD_SRV_IP_ADDRESS: 3.93.231.245
  PROD_SRV_USER: ubuntu
  SSH_PORT: 22

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Printando as coisas
        run: echo Rodando testes

  docker-build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: luanleiteti/chatapp:latest

  deploy-ec2:
    name: Deploy EC2
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
    - name: Deploy da imagem buildada
      uses: appleboy/ssh-action@master
      with:
        host: 3.93.231.245
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          sudo docker image pull luanleiteti/chatapp:latest
          sudo docker container rm -f app 
          sudo docker container run -d --restart=always --name=app -p 3000:3000 luanleiteti/chatapp:latest
